#!/bin/bash -l
#:
#PBS -N FCN_color
#PBS -l ngpus=1
#PBS -l ncpus=1
#PBS -l mem=4GB
#PBS -l walltime=4:00:00

module load python
module load caffe
module load cuda

USEGPU='true'
if [[ $(lsb_release -si) == *"SUSE LINUX"* ]]; then
    # On HPC (probably)

    # Old GPU ID method only works on nodes with 2x GPUs
    # GPU_ID=$(nvidia-smi | awk '{ if(NR==19) if($2>0) print 0; else print 1 }')

    # New GPU ID method works on nodes with 1 or more GPUs
    PROCESSES=$((nvidia-smi -q -d pids | grep Processes) | awk '{printf "%sHereBro ",$3}')
    ind=0
    GPU_ID=-1
    for process in $PROCESSES; do
        echo $process
        if [[ "$process" == "NoneHereBro" ]]; then
            GPU_ID=$ind
            break
        fi
        ind=$[ind + 1]
    done
else
    # Not on HPC (probably)
    GPU_ID=$(nvidia-smi --list-gpus | awk '{NR;}END {print NR-1}') # Grabs number of GPUS
fi

if [ $USEGPU == 'true' ]; then
    echo "Using gpu: $GPU_ID"
    export CUDA_VISIBLE_DEVICES=$GPU_ID
    gpu=$GPU_ID
else
    echo "Using cpu"
    gpu=-1
fi

if [$HOME='/home/sean']; then
  python_script=$HOME'/hpc-home/Fully-Conv-Network/Resources/FCN_models/cstrip-fcn32s-color/solve.py'
fi
if [$HOME='/home/n8307628']; then
  python_script=$HOME'/Fully-Conv-Network/Resources/FCN_models/cstrip-fcn32s-color/solve.py'
  # Because using MKL Blas on HPC
  export MKL_CBWR=AUTO
fi
current_date=`date +%Y-%m-%d.%H:%M:%S`

python $python_script 2>&1 | tee "FCNcolor_train_$current_date.log"
